apiVersion: v1
kind: PersistentVolume
metadata:
  name: volumen-mysql-esclau1
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /volume1/Kubernetes_MySQL_Esclau1
    server: 10.110.14.143
